SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY DATETIME
LIMIT 3;

-- EXCLUSIVE JOIN: 두개를 JOIN한다면 둘중 한가지 테이블에만 있는 데이터를 가져옴
-- 어느 특정 테이블에 있는 레코드만 가져옴