SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

-- HAVING: GROUP BY 다음에 수행되는 WHERE 같은 절
-- 컬럼의 총 갯수가 어떤 숫자 초과인 경우 `COUNT(column) > 숫자` 형태로 사용